export const SIGN_UP = "Sign Up";
export const ACTIVATE = "Activate";
export const LOGIN = "Login";
export const RESEND = "Resend?";
export const LOGOUT = "Logout";
export const DELETE = "Delete";
export const CHANGE = "Change";
export const ADD_FRIEND = "Add Friend";
export const ACCEPT = "Accept";
